function Hd = BPF(F0, BW, G)
%BPF Returns a discrete-time filter object.


% MATLAB Code
% Generated by MATLAB(R) 9.3 and DSP System Toolbox 9.5.
% Generated on: 09-May-2018 10:50:39

% Chebyshev Type II Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = 44100;  % Sampling Frequency

Fstop1 = F0-BW-BW/2;        % First Stopband Frequency
if (Fstop1 < 0)
    Fstop1 = 1;
end

Fpass1 = F0-BW;        % First Passband Frequency

if (Fpass1 < 0)
    Fpass1 = 1;
end

Fpass2 = F0+BW;       % Second Passband Frequency
Fstop2 = F0+BW+BW/2;       % Second Stopband Frequency
Astop1 = 30;          % First Stopband Attenuation (dB)
Apass  = 1;           % Passband Ripple (dB)
Astop2 = 30;          % Second Stopband Attenuation (dB)
match  = 'passband';  % Band to match exactly

% Construct an FDESIGN object and call its CHEBY2 method.
h  = fdesign.bandpass(Fstop1, Fpass1, Fpass2, Fstop2, Astop1, Apass, ...
                      Astop2, Fs);
Hd = design(h, 'cheby2', 'MatchExactly', match);
% [EOF]
end

